Repository kyma-project/cfapi, pull requests merged in 2024-08, with the labels that each got.

#32 Adopt docker registry kyma module
  config/rbac/role.yaml
  controllers/cfapi_controller_rendered_resources.go
  controllers/install_twuni.go
  module-data/docker-registry/docker-registry.yaml
  module-data/twuni-certificate/certificate.tmpl
  module-data/twuni-dns-entry/dnsentry.tmpl
  module-data/twuni-referencegrant/referencegrant.yaml
  module-data/twuni-tlsroute/tlsroute.tmpl
Labels: cla: yes, size/L, lgtm

#33 Create build-korifi.yml
  .github/workflows/build-korifi.yml
Labels: cla: yes, size/M

#34 Update build-korifi.yml
  .github/workflows/build-korifi.yml
Labels: cla: yes

#35 Wf/korifi release
  .github/workflows/build-korifi.yml
  scripts/create-korifi-release.sh
Labels: cla: yes, size/M

#36 Update build-korifi.yml
  .github/workflows/build-korifi.yml
Labels: cla: yes, size/XS

#37 Update build-korifi.yml
  .github/workflows/build-korifi.yml
Labels: cla: yes, size/XS

#38 Update build-korifi.yml
  .github/workflows/build-korifi.yml
Labels: cla: yes, size/XS

#39 Update build-korifi.yml
  .github/workflows/build-korifi.yml
Labels: cla: yes, size/XS

#40 Update build-korifi.yml
  .github/workflows/build-korifi.yml
Labels: cla: yes, size/XS

#41 Update build-korifi.yml
  .github/workflows/build-korifi.yml
Labels: cla: yes, size/XS

#43 Update README.md
  README.md
Labels: cla: yes, size/S

#44 add genkubeconfig docker image
  .github/workflows/release-genkubeconfig.yml
  tools/kubeconfig/Dockerfile
  tools/kubeconfig/gen-kubeconfig.sh
  tools/kubeconfig/serviceaccount.yaml
Labels: cla: yes, size/L

#45 Update release-genkubeconfig.yml
  .github/workflows/release-genkubeconfig.yml
Labels: cla: yes, size/XS

#47 add +x to gen-kubeconfig executable
  tools/kubeconfig/gen-kubeconfig.sh
Labels: cla: yes, size/XS

#48 Update README.md
  README.md
Labels: cla: yes

#49 Update README.md
  README.md
Labels: cla: yes, size/XS

#50 Update README.md
  README.md
Labels: cla: yes, size/XS

#59 update + tidy deps
  Makefile
  api/go.mod
  api/go.sum
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/cfapi_auth.go
  controllers/cfapi_controller_rendered_resources.go
  controllers/cfapi_controller_rendered_resources_test.go
  controllers/common_utils.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  module-data/README.md
  scripts/release/create_changelog.sh
  scripts/release/draft_release.sh
  scripts/release/publish_release.sh
  scripts/release/upload_assets.sh
  scripts/release/validate_pipeline_status.sh
  scripts/release/validate_versions.sh
Labels: cla: yes, size/L

#60 added build korifi steps to the workflow
  .github/workflows/run-kyma.yml
Labels: cla: yes, size/S
