Repository kyma-project/cfapi, pull requests merged in 2024-09, with the labels that each got.

#61 preparing rel 0.0.7
  .github/workflows/release.yml
  RELEASE.md
Labels: cla: yes, size/XS

#62 new publish release workflow
  .github/workflows/release-publish.yml
Labels: cla: yes, size/S

#63 fix to become reuse compliant
  .reuse/dep5
  REUSE.toml
  api/v1alpha1/cfapi_types.go
  api/v1alpha1/managed_types.go
  api/v1alpha1/status.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/cfapi_auth.go
  controllers/cfapi_controller_rendered_resources.go
  controllers/cfapi_controller_rendered_resources_test.go
  controllers/suite_test.go
  main.go
Labels: cla: yes, size/M

#67 adapt to incompatible change in docker registry
  module-data/docker-registry/docker-registry.yaml
Labels: cla: yes, size/XS

#68 Update RELEASE.md
  RELEASE.md
Labels: cla: yes, size/XS

#69 fix oidc resource
  config/rbac/role.yaml
  controllers/cfapi_controller_rendered_resources.go
Labels: cla: yes, size/S

#70 Reuse fix
  .reuse/dep5
  README.md
Labels: cla: yes, size/M

#72 fix sap.ids prefix
  controllers/cfapi_auth.go
Labels: cla: yes, size/XS
