Repository kyma-project/cfapi, pull requests merged in 2024-07, with the labels that each got.

#10 add workflow
  .github/workflows/makefile.yml
Labels: cla: yes, size/M

#12 Update makefile.yml
  .github/workflows/makefile.yml
Labels: cla: yes, size/XS

#13 Update makefile.yml
  .github/workflows/makefile.yml
Labels: cla: yes, size/S

#14 Improve helm release lifecycle
  controllers/cfapi_controller_rendered_resources.go
  controllers/helm_utils.go
  controllers/install_twuni.go
Labels: cla: yes, lgtm, size/XL

#15 Workflow release
  .github/workflows/release.yml
  Makefile
  module-data/korifi/korifi-helm-0.11.0.tar.gz
  module-data/korifi/korifi-helm-0.11.2.tar.gz
  module-data/korifi/values-0.11.2.yaml
Labels: cla: yes, size/L

#16 remove cfapi-system-registry secret
  RELEASE.md
  config/rbac/service_account.yaml
  controllers/cfapi_controller_rendered_resources.go
  controllers/k8s_utils.go
  docs/user/Setup-Prod.md
  module-data/korifi/values.yaml
Labels: cla: yes, size/M

#17 make release with gh
  .github/workflows/release.yml
Labels: cla: yes, size/S

#21 Update release.yml
  .github/workflows/release.yml
Labels: cla: yes

#22 fix release workflow 5
  .github/workflows/release.yml
Labels: cla: yes, size/L

#23 Update README.md
  README.md
Labels: cla: yes, size/L

#24 fix curl -OLF dependency downloads
  Dockerfile
Labels: cla: yes, size/S, lgtm

#26 Extend GITHUB_TOKEN permissions
  .github/workflows/release.yml
Labels: cla: yes, size/XS, lgtm

#27 Fix controller cluster role
  config/rbac/role.yaml
Labels: cla: yes, size/XS, lgtm

#28 Update korifi helm chart
  module-data/korifi/korifi-helm-0.11.2.tar.gz
Labels: cla: yes, size/XS, lgtm

#30 Fix korifi helm chart archive
  module-data/korifi/korifi-helm-0.11.2.tar.gz
Labels: cla: yes, size/XS, lgtm
