Repository kyma-project/cfapi, pull requests merged in 2025-01, with the labels that each got.

#90 Osskorifi
  .github/workflows/release-draft.yml
  Dockerfile
  Makefile
Labels: cla: yes, size/S

#95 Fix DNS entries creation
  controllers/cfapi_controller_rendered_resources.go
Labels: cla: yes, size/XS, lgtm

#96 Fix UAA URL in OIDC config creation
  controllers/cfapi_controller_rendered_resources.go
Labels: cla: yes, size/S, lgtm

#97 Rel 0.2.0
  README.md
  RELEASE.md
  config/crd/bases/operator.kyma-project.io_cfapis.yaml
  controllers/cfapi_auth.go
  controllers/cfapi_controller_rendered_resources.go
Labels: cla: yes, size/L
